CREATE TABLE public.ako_coupons (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  creator_id INTEGER NOT NULL,
  season_id INTEGER NOT NULL,
  ako_round_number INTEGER NOT NULL,
  total_odds NUMERIC NOT NULL,
  hit_count INTEGER NOT NULL,
  is_hit BOOLEAN NOT NULL,
  link TEXT,
  CONSTRAINT ako_coupons_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES public.players (id),
  CONSTRAINT ako_coupons_season_id_fkey FOREIGN KEY (season_id) REFERENCES public.seasons (id)
);
