create table public.picks (
  id INTEGER generated by default as identity primary key,
  player_id INTEGER not null,
  season_id INTEGER not null,
  matchday_id INTEGER not null,
  league_id INTEGER,
  odds NUMERIC not null,
  is_hit BOOLEAN not null,
  votes INTEGER not null default 0,
  is_chosen BOOLEAN not null default false,
  constraint picks_matchday_id_fkey foreign KEY (matchday_id) references public.matchdays (id),
  constraint picks_player_id_fkey foreign KEY (player_id) references public.players (id),
  constraint picks_season_id_fkey foreign KEY (season_id) references public.seasons (id),
  constraint picks_league_id_fkey foreign KEY (league_id) references public.leagues (id)
);

create unique index uniq_pick_per_player_per_round on picks (player_id, matchday_id);
