CREATE TABLE public.picks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id INTEGER NOT NULL,
  season_id INTEGER NOT NULL,
  matchday_id INTEGER NOT NULL,
  league_id INTEGER,
  odds NUMERIC NOT NULL,
  is_hit BOOLEAN NOT NULL,
  votes INTEGER NOT NULL DEFAULT 0,
  is_chosen BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT picks_matchday_id_fkey FOREIGN KEY (matchday_id) REFERENCES public.matchdays (id) ON DELETE CASCADE,
  CONSTRAINT picks_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players (id),
  CONSTRAINT picks_season_id_fkey FOREIGN KEY (season_id) REFERENCES public.seasons (id),
  CONSTRAINT picks_league_id_fkey FOREIGN KEY (league_id) REFERENCES public.leagues (id)
);

CREATE UNIQUE INDEX uniq_pick_per_player_per_round ON picks (player_id, matchday_id);

ALTER TABLE public.picks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Picks are viewable by everyone" ON public.picks FOR
SELECT
  USING (TRUE);

CREATE POLICY "Only authenticated users can insert picks" ON public.picks FOR INSERT
WITH
  CHECK (auth.uid () IS NOT NULL);

CREATE POLICY "Only authenticated users can update picks" ON public.picks
FOR UPDATE
  USING (auth.uid () IS NOT NULL)
WITH
  CHECK (auth.uid () IS NOT NULL);

CREATE POLICY "Only authenticated users can delete picks" ON public.picks FOR DELETE USING (auth.uid () IS NOT NULL);
