CREATE TABLE public.picks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id INTEGER NOT NULL,
  season_id INTEGER NOT NULL,
  matchday_id INTEGER NOT NULL,
  league_id INTEGER,
  odds NUMERIC NOT NULL,
  is_hit BOOLEAN NOT NULL,
  votes INTEGER NOT NULL DEFAULT 0,
  is_chosen BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT picks_matchday_id_fkey FOREIGN KEY (matchday_id) REFERENCES public.matchdays(id),
  CONSTRAINT picks_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id),
  CONSTRAINT picks_season_id_fkey FOREIGN KEY (season_id) REFERENCES public.seasons(id),
  CONSTRAINT picks_league_id_fkey FOREIGN KEY (league_id) REFERENCES public.leagues(id)
);
