CREATE TABLE public.players (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL
);

ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Players are viewable by everyone" ON public.players FOR
SELECT
  USING (TRUE);

CREATE POLICY "Only authenticated users can insert players" ON public.players FOR INSERT
WITH
  CHECK (auth.uid () IS NOT NULL);

CREATE POLICY "Only authenticated users can update players" ON public.players
FOR UPDATE
  USING (auth.uid () IS NOT NULL)
WITH
  CHECK (auth.uid () IS NOT NULL);

CREATE POLICY "Only authenticated users can delete players" ON public.players FOR DELETE USING (auth.uid () IS NOT NULL);
