CREATE TABLE public.round_types (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

ALTER TABLE public.round_types ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Round types are viewable by everyone" ON public.round_types FOR
SELECT
  USING (TRUE);

CREATE POLICY "Only authenticated users can insert round types" ON public.round_types FOR INSERT
WITH
  CHECK (auth.uid () IS NOT NULL);

CREATE POLICY "Only authenticated users can update round types" ON public.round_types
FOR UPDATE
  USING (auth.uid () IS NOT NULL)
WITH
  CHECK (auth.uid () IS NOT NULL);

CREATE POLICY "Only authenticated users can delete round types" ON public.round_types FOR DELETE USING (auth.uid () IS NOT NULL);
