CREATE TABLE public.votes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id INTEGER NOT NULL,
  pick_id INTEGER,
  CONSTRAINT votes_pick_id_fkey FOREIGN KEY (pick_id) REFERENCES public.picks (id) ON DELETE CASCADE,
  CONSTRAINT votes_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players (id)
);
