create table "public"."ako_coupons" (
    "id" integer generated by default as identity not null,
    "creator_id" integer not null,
    "season_id" integer not null,
    "ako_round_number" integer not null,
    "total_odds" numeric not null,
    "hit_count" integer not null,
    "is_hit" boolean not null,
    "link" text
);


create table "public"."leagues" (
    "id" integer generated by default as identity not null,
    "name" text not null,
    "country" text not null,
    "level" integer not null
);


create table "public"."matchdays" (
    "id" integer generated by default as identity not null,
    "season_id" integer,
    "related_matchday_id" integer,
    "round_type_id" integer not null,
    "round_number" integer not null,
    "match_date" date not null,
    "correct" boolean not null default false
);


create table "public"."picks" (
    "id" integer generated by default as identity not null,
    "player_id" integer not null,
    "season_id" integer not null,
    "matchday_id" integer not null,
    "league_id" integer not null,
    "odds" numeric not null,
    "is_hit" boolean not null,
    "votes" integer not null default 0,
    "is_chosen" boolean not null default false
);


create table "public"."players" (
    "id" integer generated by default as identity not null,
    "username" text not null
);


create table "public"."round_types" (
    "id" integer generated by default as identity not null,
    "name" text not null
);


create table "public"."seasons" (
    "id" integer generated by default as identity not null,
    "name" text not null,
    "start_date" date not null,
    "end_date" date not null
);


create table "public"."votes" (
    "id" integer generated by default as identity not null,
    "player_id" integer not null,
    "pick_id" integer
);


CREATE UNIQUE INDEX ako_coupons_pkey ON public.ako_coupons USING btree (id);

CREATE UNIQUE INDEX leagues_pkey ON public.leagues USING btree (id);

CREATE UNIQUE INDEX matchdays_pkey ON public.matchdays USING btree (id);

CREATE UNIQUE INDEX picks_pkey ON public.picks USING btree (id);

CREATE UNIQUE INDEX players_pkey ON public.players USING btree (id);

CREATE UNIQUE INDEX players_username_key ON public.players USING btree (username);

CREATE UNIQUE INDEX round_types_name_key ON public.round_types USING btree (name);

CREATE UNIQUE INDEX round_types_pkey ON public.round_types USING btree (id);

CREATE UNIQUE INDEX seasons_pkey ON public.seasons USING btree (id);

CREATE UNIQUE INDEX votes_pkey ON public.votes USING btree (id);

alter table "public"."ako_coupons" add constraint "ako_coupons_pkey" PRIMARY KEY using index "ako_coupons_pkey";

alter table "public"."leagues" add constraint "leagues_pkey" PRIMARY KEY using index "leagues_pkey";

alter table "public"."matchdays" add constraint "matchdays_pkey" PRIMARY KEY using index "matchdays_pkey";

alter table "public"."picks" add constraint "picks_pkey" PRIMARY KEY using index "picks_pkey";

alter table "public"."players" add constraint "players_pkey" PRIMARY KEY using index "players_pkey";

alter table "public"."round_types" add constraint "round_types_pkey" PRIMARY KEY using index "round_types_pkey";

alter table "public"."seasons" add constraint "seasons_pkey" PRIMARY KEY using index "seasons_pkey";

alter table "public"."votes" add constraint "votes_pkey" PRIMARY KEY using index "votes_pkey";

alter table "public"."ako_coupons" add constraint "ako_coupons_creator_id_fkey" FOREIGN KEY (creator_id) REFERENCES players(id) not valid;

alter table "public"."ako_coupons" validate constraint "ako_coupons_creator_id_fkey";

alter table "public"."ako_coupons" add constraint "ako_coupons_season_id_fkey" FOREIGN KEY (season_id) REFERENCES seasons(id) not valid;

alter table "public"."ako_coupons" validate constraint "ako_coupons_season_id_fkey";

alter table "public"."matchdays" add constraint "matchdays_related_matchday_id_fkey" FOREIGN KEY (related_matchday_id) REFERENCES matchdays(id) not valid;

alter table "public"."matchdays" validate constraint "matchdays_related_matchday_id_fkey";

alter table "public"."matchdays" add constraint "matchdays_round_type_id_fkey" FOREIGN KEY (round_type_id) REFERENCES round_types(id) not valid;

alter table "public"."matchdays" validate constraint "matchdays_round_type_id_fkey";

alter table "public"."matchdays" add constraint "matchdays_season_id_fkey" FOREIGN KEY (season_id) REFERENCES seasons(id) not valid;

alter table "public"."matchdays" validate constraint "matchdays_season_id_fkey";

alter table "public"."picks" add constraint "picks_league_id_fkey" FOREIGN KEY (league_id) REFERENCES leagues(id) not valid;

alter table "public"."picks" validate constraint "picks_league_id_fkey";

alter table "public"."picks" add constraint "picks_matchday_id_fkey" FOREIGN KEY (matchday_id) REFERENCES matchdays(id) not valid;

alter table "public"."picks" validate constraint "picks_matchday_id_fkey";

alter table "public"."picks" add constraint "picks_player_id_fkey" FOREIGN KEY (player_id) REFERENCES players(id) not valid;

alter table "public"."picks" validate constraint "picks_player_id_fkey";

alter table "public"."picks" add constraint "picks_season_id_fkey" FOREIGN KEY (season_id) REFERENCES seasons(id) not valid;

alter table "public"."picks" validate constraint "picks_season_id_fkey";

alter table "public"."players" add constraint "players_username_key" UNIQUE using index "players_username_key";

alter table "public"."round_types" add constraint "round_types_name_key" UNIQUE using index "round_types_name_key";

alter table "public"."votes" add constraint "votes_pick_id_fkey" FOREIGN KEY (pick_id) REFERENCES picks(id) not valid;

alter table "public"."votes" validate constraint "votes_pick_id_fkey";

alter table "public"."votes" add constraint "votes_player_id_fkey" FOREIGN KEY (player_id) REFERENCES players(id) not valid;

alter table "public"."votes" validate constraint "votes_player_id_fkey";

grant delete on table "public"."ako_coupons" to "anon";

grant insert on table "public"."ako_coupons" to "anon";

grant references on table "public"."ako_coupons" to "anon";

grant select on table "public"."ako_coupons" to "anon";

grant trigger on table "public"."ako_coupons" to "anon";

grant truncate on table "public"."ako_coupons" to "anon";

grant update on table "public"."ako_coupons" to "anon";

grant delete on table "public"."ako_coupons" to "authenticated";

grant insert on table "public"."ako_coupons" to "authenticated";

grant references on table "public"."ako_coupons" to "authenticated";

grant select on table "public"."ako_coupons" to "authenticated";

grant trigger on table "public"."ako_coupons" to "authenticated";

grant truncate on table "public"."ako_coupons" to "authenticated";

grant update on table "public"."ako_coupons" to "authenticated";

grant delete on table "public"."ako_coupons" to "service_role";

grant insert on table "public"."ako_coupons" to "service_role";

grant references on table "public"."ako_coupons" to "service_role";

grant select on table "public"."ako_coupons" to "service_role";

grant trigger on table "public"."ako_coupons" to "service_role";

grant truncate on table "public"."ako_coupons" to "service_role";

grant update on table "public"."ako_coupons" to "service_role";

grant delete on table "public"."leagues" to "anon";

grant insert on table "public"."leagues" to "anon";

grant references on table "public"."leagues" to "anon";

grant select on table "public"."leagues" to "anon";

grant trigger on table "public"."leagues" to "anon";

grant truncate on table "public"."leagues" to "anon";

grant update on table "public"."leagues" to "anon";

grant delete on table "public"."leagues" to "authenticated";

grant insert on table "public"."leagues" to "authenticated";

grant references on table "public"."leagues" to "authenticated";

grant select on table "public"."leagues" to "authenticated";

grant trigger on table "public"."leagues" to "authenticated";

grant truncate on table "public"."leagues" to "authenticated";

grant update on table "public"."leagues" to "authenticated";

grant delete on table "public"."leagues" to "service_role";

grant insert on table "public"."leagues" to "service_role";

grant references on table "public"."leagues" to "service_role";

grant select on table "public"."leagues" to "service_role";

grant trigger on table "public"."leagues" to "service_role";

grant truncate on table "public"."leagues" to "service_role";

grant update on table "public"."leagues" to "service_role";

grant delete on table "public"."matchdays" to "anon";

grant insert on table "public"."matchdays" to "anon";

grant references on table "public"."matchdays" to "anon";

grant select on table "public"."matchdays" to "anon";

grant trigger on table "public"."matchdays" to "anon";

grant truncate on table "public"."matchdays" to "anon";

grant update on table "public"."matchdays" to "anon";

grant delete on table "public"."matchdays" to "authenticated";

grant insert on table "public"."matchdays" to "authenticated";

grant references on table "public"."matchdays" to "authenticated";

grant select on table "public"."matchdays" to "authenticated";

grant trigger on table "public"."matchdays" to "authenticated";

grant truncate on table "public"."matchdays" to "authenticated";

grant update on table "public"."matchdays" to "authenticated";

grant delete on table "public"."matchdays" to "service_role";

grant insert on table "public"."matchdays" to "service_role";

grant references on table "public"."matchdays" to "service_role";

grant select on table "public"."matchdays" to "service_role";

grant trigger on table "public"."matchdays" to "service_role";

grant truncate on table "public"."matchdays" to "service_role";

grant update on table "public"."matchdays" to "service_role";

grant delete on table "public"."picks" to "anon";

grant insert on table "public"."picks" to "anon";

grant references on table "public"."picks" to "anon";

grant select on table "public"."picks" to "anon";

grant trigger on table "public"."picks" to "anon";

grant truncate on table "public"."picks" to "anon";

grant update on table "public"."picks" to "anon";

grant delete on table "public"."picks" to "authenticated";

grant insert on table "public"."picks" to "authenticated";

grant references on table "public"."picks" to "authenticated";

grant select on table "public"."picks" to "authenticated";

grant trigger on table "public"."picks" to "authenticated";

grant truncate on table "public"."picks" to "authenticated";

grant update on table "public"."picks" to "authenticated";

grant delete on table "public"."picks" to "service_role";

grant insert on table "public"."picks" to "service_role";

grant references on table "public"."picks" to "service_role";

grant select on table "public"."picks" to "service_role";

grant trigger on table "public"."picks" to "service_role";

grant truncate on table "public"."picks" to "service_role";

grant update on table "public"."picks" to "service_role";

grant delete on table "public"."players" to "anon";

grant insert on table "public"."players" to "anon";

grant references on table "public"."players" to "anon";

grant select on table "public"."players" to "anon";

grant trigger on table "public"."players" to "anon";

grant truncate on table "public"."players" to "anon";

grant update on table "public"."players" to "anon";

grant delete on table "public"."players" to "authenticated";

grant insert on table "public"."players" to "authenticated";

grant references on table "public"."players" to "authenticated";

grant select on table "public"."players" to "authenticated";

grant trigger on table "public"."players" to "authenticated";

grant truncate on table "public"."players" to "authenticated";

grant update on table "public"."players" to "authenticated";

grant delete on table "public"."players" to "service_role";

grant insert on table "public"."players" to "service_role";

grant references on table "public"."players" to "service_role";

grant select on table "public"."players" to "service_role";

grant trigger on table "public"."players" to "service_role";

grant truncate on table "public"."players" to "service_role";

grant update on table "public"."players" to "service_role";

grant delete on table "public"."round_types" to "anon";

grant insert on table "public"."round_types" to "anon";

grant references on table "public"."round_types" to "anon";

grant select on table "public"."round_types" to "anon";

grant trigger on table "public"."round_types" to "anon";

grant truncate on table "public"."round_types" to "anon";

grant update on table "public"."round_types" to "anon";

grant delete on table "public"."round_types" to "authenticated";

grant insert on table "public"."round_types" to "authenticated";

grant references on table "public"."round_types" to "authenticated";

grant select on table "public"."round_types" to "authenticated";

grant trigger on table "public"."round_types" to "authenticated";

grant truncate on table "public"."round_types" to "authenticated";

grant update on table "public"."round_types" to "authenticated";

grant delete on table "public"."round_types" to "service_role";

grant insert on table "public"."round_types" to "service_role";

grant references on table "public"."round_types" to "service_role";

grant select on table "public"."round_types" to "service_role";

grant trigger on table "public"."round_types" to "service_role";

grant truncate on table "public"."round_types" to "service_role";

grant update on table "public"."round_types" to "service_role";

grant delete on table "public"."seasons" to "anon";

grant insert on table "public"."seasons" to "anon";

grant references on table "public"."seasons" to "anon";

grant select on table "public"."seasons" to "anon";

grant trigger on table "public"."seasons" to "anon";

grant truncate on table "public"."seasons" to "anon";

grant update on table "public"."seasons" to "anon";

grant delete on table "public"."seasons" to "authenticated";

grant insert on table "public"."seasons" to "authenticated";

grant references on table "public"."seasons" to "authenticated";

grant select on table "public"."seasons" to "authenticated";

grant trigger on table "public"."seasons" to "authenticated";

grant truncate on table "public"."seasons" to "authenticated";

grant update on table "public"."seasons" to "authenticated";

grant delete on table "public"."seasons" to "service_role";

grant insert on table "public"."seasons" to "service_role";

grant references on table "public"."seasons" to "service_role";

grant select on table "public"."seasons" to "service_role";

grant trigger on table "public"."seasons" to "service_role";

grant truncate on table "public"."seasons" to "service_role";

grant update on table "public"."seasons" to "service_role";

grant delete on table "public"."votes" to "anon";

grant insert on table "public"."votes" to "anon";

grant references on table "public"."votes" to "anon";

grant select on table "public"."votes" to "anon";

grant trigger on table "public"."votes" to "anon";

grant truncate on table "public"."votes" to "anon";

grant update on table "public"."votes" to "anon";

grant delete on table "public"."votes" to "authenticated";

grant insert on table "public"."votes" to "authenticated";

grant references on table "public"."votes" to "authenticated";

grant select on table "public"."votes" to "authenticated";

grant trigger on table "public"."votes" to "authenticated";

grant truncate on table "public"."votes" to "authenticated";

grant update on table "public"."votes" to "authenticated";

grant delete on table "public"."votes" to "service_role";

grant insert on table "public"."votes" to "service_role";

grant references on table "public"."votes" to "service_role";

grant select on table "public"."votes" to "service_role";

grant trigger on table "public"."votes" to "service_role";

grant truncate on table "public"."votes" to "service_role";

grant update on table "public"."votes" to "service_role";


